Repository hashicorp/envconsul, pull requests merged in 2022-07, with the labels that each got.

#281 Support Vault Auth method
  README.md
  cli.go
  cli_test.go
  runner.go
Labels: enhancement, vault

#304 fix command parsing needed due to upstream changes
  go.mod
  go.sum
  runner.go
Labels: bug

#303 have standard 'log' package output to hclog + ERROR level tweaks
  cli.go
Labels: enhancement

#306 only setpgid on child calls if subshell is used
  go.mod
  go.sum
  runner.go
Labels: bug
